import React, { useState, useMemo } from 'react';
import { useQuery } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { FileText, Download, ArrowUpDown, ArrowUp, ArrowDown, FileBarChart2 } from 'lucide-react';
import { format, parseISO } from 'date-fns';

const DIVISION_COLORS = {
  East: 'bg-blue-100 text-blue-700',
  Midwest: 'bg-purple-100 text-purple-700',
  Southwest: 'bg-orange-100 text-orange-700',
  Mountain: 'bg-emerald-100 text-emerald-700',
};

function SortHeader({ label, field, sortField, sortDir, onSort }) {
  const active = sortField === field;
  return (
    <button
      onClick={() => onSort(field)}
      className="flex items-center gap-1 text-xs font-semibold text-slate-500 uppercase tracking-wide hover:text-slate-700"
    >
      {label}
      {active ? (
        sortDir === 'asc' ? <ArrowUp className="w-3 h-3" /> : <ArrowDown className="w-3 h-3" />
      ) : (
        <ArrowUpDown className="w-3 h-3 opacity-40" />
      )}
    </button>
  );
}

export default function DivisionReportsTab() {
  const [divisionFilter, setDivisionFilter] = useState('all');
  const [generatedByFilter, setGeneratedByFilter] = useState('all');
  const [dateFrom, setDateFrom] = useState('');
  const [dateTo, setDateTo] = useState('');
  const [sortField, setSortField] = useState('generated_at');
  const [sortDir, setSortDir] = useState('desc');

  const { data: reports = [], isLoading } = useQuery({
    queryKey: ['divisionReports'],
    queryFn: () => base44.entities.DivisionReport.list(),
  });

  const handleSort = (field) => {
    if (sortField === field) {
      setSortDir(d => d === 'asc' ? 'desc' : 'asc');
    } else {
      setSortField(field);
      setSortDir('desc');
    }
  };

  const filtered = useMemo(() => {
    let list = [...reports];

    if (divisionFilter !== 'all') list = list.filter(r => r.division === divisionFilter);
    if (generatedByFilter !== 'all') list = list.filter(r => r.generated_by === generatedByFilter);
    if (dateFrom) list = list.filter(r => r.week_of >= dateFrom);
    if (dateTo) list = list.filter(r => r.week_of <= dateTo);

    list.sort((a, b) => {
      let valA = a[sortField] ?? '';
      let valB = b[sortField] ?? '';
      if (sortField === 'week_number') {
        valA = Number(valA);
        valB = Number(valB);
      }
      if (valA < valB) return sortDir === 'asc' ? -1 : 1;
      if (valA > valB) return sortDir === 'asc' ? 1 : -1;
      return 0;
    });

    return list;
  }, [reports, divisionFilter, generatedByFilter, dateFrom, dateTo, sortField, sortDir]);

  return (
    <Card className="border-0 shadow-sm">
      <CardHeader className="pb-4">
        {/* Filters */}
        <div className="flex flex-wrap gap-3 items-end">
          <div className="space-y-1">
            <Label className="text-xs text-slate-500">Division</Label>
            <Select value={divisionFilter} onValueChange={setDivisionFilter}>
              <SelectTrigger className="w-36 h-8 text-sm">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Divisions</SelectItem>
                <SelectItem value="East">East</SelectItem>
                <SelectItem value="Midwest">Midwest</SelectItem>
                <SelectItem value="Southwest">Southwest</SelectItem>
                <SelectItem value="Mountain">Mountain</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-1">
            <Label className="text-xs text-slate-500">Generated By</Label>
            <Select value={generatedByFilter} onValueChange={setGeneratedByFilter}>
              <SelectTrigger className="w-36 h-8 text-sm">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All</SelectItem>
                <SelectItem value="Scheduled">Scheduled</SelectItem>
                <SelectItem value="Manual">Manual</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-1">
            <Label className="text-xs text-slate-500">Week Of — From</Label>
            <Input
              type="date"
              value={dateFrom}
              onChange={e => setDateFrom(e.target.value)}
              className="h-8 text-sm w-36"
            />
          </div>

          <div className="space-y-1">
            <Label className="text-xs text-slate-500">Week Of — To</Label>
            <Input
              type="date"
              value={dateTo}
              onChange={e => setDateTo(e.target.value)}
              className="h-8 text-sm w-36"
            />
          </div>

          {(divisionFilter !== 'all' || generatedByFilter !== 'all' || dateFrom || dateTo) && (
            <Button
              variant="ghost"
              size="sm"
              className="h-8 text-slate-400 hover:text-slate-600 self-end"
              onClick={() => { setDivisionFilter('all'); setGeneratedByFilter('all'); setDateFrom(''); setDateTo(''); }}
            >
              Clear filters
            </Button>
          )}
        </div>
      </CardHeader>

      <CardContent>
        {isLoading ? (
          <div className="text-center py-12 text-slate-400 text-sm">Loading reports...</div>
        ) : reports.length === 0 ? (
          <div className="text-center py-16 text-slate-500">
            <FileBarChart2 className="w-12 h-12 mx-auto mb-4 opacity-30" />
            <p className="font-medium">No division reports have been generated yet.</p>
            <p className="text-sm text-slate-400 mt-1">Use the "Generate Reports Now" button to create your first report.</p>
          </div>
        ) : filtered.length === 0 ? (
          <div className="text-center py-12 text-slate-400 text-sm">No reports match the selected filters.</div>
        ) : (
          <div className="overflow-x-auto">
            {/* Table header */}
            <div className="grid grid-cols-[1fr_90px_140px_160px_110px_120px] gap-3 px-3 py-2 mb-1">
              <SortHeader label="Division" field="division" sortField={sortField} sortDir={sortDir} onSort={handleSort} />
              <SortHeader label="Week" field="week_number" sortField={sortField} sortDir={sortDir} onSort={handleSort} />
              <SortHeader label="Week Of" field="week_of" sortField={sortField} sortDir={sortDir} onSort={handleSort} />
              <SortHeader label="Generated At" field="generated_at" sortField={sortField} sortDir={sortDir} onSort={handleSort} />
              <SortHeader label="Source" field="generated_by" sortField={sortField} sortDir={sortDir} onSort={handleSort} />
              <span className="text-xs font-semibold text-slate-500 uppercase tracking-wide">PDF</span>
            </div>

            <div className="space-y-2">
              {filtered.map(report => (
                <div
                  key={report.id}
                  className="grid grid-cols-[1fr_90px_140px_160px_110px_120px] gap-3 items-center px-3 py-3 bg-slate-50 rounded-lg border border-slate-100 hover:bg-white transition-colors"
                >
                  {/* Division */}
                  <Badge className={`w-fit text-xs font-medium ${DIVISION_COLORS[report.division] || 'bg-slate-100 text-slate-600'}`}>
                    {report.division}
                  </Badge>

                  {/* Week number */}
                  <span className="text-sm font-medium text-slate-700">Week {report.week_number}</span>

                  {/* Week of */}
                  <span className="text-sm text-slate-600">
                    {report.week_of
                      ? format(parseISO(report.week_of), 'EEE, MMM d, yyyy')
                      : '—'}
                  </span>

                  {/* Generated at */}
                  <span className="text-sm text-slate-500">
                    {report.generated_at
                      ? format(new Date(report.generated_at), 'MMM d, yyyy h:mm a')
                      : '—'}
                  </span>

                  {/* Generated by */}
                  <Badge className={report.generated_by === 'Scheduled'
                    ? 'bg-emerald-100 text-emerald-700 w-fit text-xs'
                    : 'bg-slate-100 text-slate-600 w-fit text-xs'
                  }>
                    {report.generated_by}
                  </Badge>

                  {/* Download */}
                  {report.pdf_file ? (
                    <Button
                      variant="outline"
                      size="sm"
                      className="h-7 text-xs gap-1 w-fit"
                      onClick={() => window.open(report.pdf_file, '_blank')}
                    >
                      <Download className="w-3 h-3" />
                      Download
                    </Button>
                  ) : (
                    <span className="text-xs text-slate-400">No file</span>
                  )}
                </div>
              ))}
            </div>

            <p className="text-xs text-slate-400 mt-4 text-right">
              Showing {filtered.length} of {reports.length} report{reports.length !== 1 ? 's' : ''}
            </p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}